export const SET_STATUS = 'SET_STATUS'
export const SET_TIMER = 'SET_TIMER'
export const SET_START_TIME = 'SET_START_TIME'
export const SET_DURATION = 'SET_DURATION'
export const SET_ERROR = 'SET_ERROR'
export const SET_TEAMS = 'SET_TEAMS'
export const SET_FIELD = 'SET_FIELD'
export const SET_CURRENT = 'SET_CURRENT'
